# Generated by Django 5.1.1 on 2024-12-28 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialgoal',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
