# Generated by Django 5.1.1 on 2024-12-28 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_debtrepaymentgoal_financialsavinggoal_personalgoal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debtrepaymentgoal',
            name='minimum_payment',
        ),
    ]
