services:
  - type: web
    name: django-backend
    runtime: python
    region: oregon
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --no-input && python manage.py migrate"
    startCommand: "gunicorn backend.wsgi:application --bind 0.0.0.0:10000"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: django-db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "your-app-name.onrender.com"
      - key: PORT
        value: "10000"

databases:
  - name: django-db
    plan: free

  - type: static
    name: react-frontend
    buildCommand: "npm install && npm run build"
    publishPath: "frontend/build"
    envVars:
      - key: REACT_APP_API_URL
        value: "https://django-backend.onrender.com/api"
